### ISSUE TITLE
Unknown argument '-n'

### ISSUE THREAD

**Issue by sickill** [jcoglan/vault#28] opened 2015-01-22 11:07 UTC
When trying to store note with `-n` switch I'm getting the following error:

```
$ vault -c -n foo
Unknown argument '-n'.
```

vault v0.3.0, node v0.10.32

**Comment by sickill** [comment] 2015-01-22 11:13
I see notes have been added after 0.3.0 release. Any plans to release 0.4.0?

**Comment by gardenvarietyse** [comment] 2017-03-09 11:58
I too would like to know the answer to this question

**Comment by jcoglan** [comment] 2017-03-10 18:38
Unfortunately I'm not able to work on Vault as often as I'd like, but I still use it daily and want to push it forward. The codebase that was planned for 0.4 has taken a long time to get into a shape where I'd be happy releasing it, including various half-finished ideas.

I did some work last year to develop http://github.com/jcoglan/storeroom, which will form the new storage backend for Vault, which massively cleans up the internal architecture of the project. I was in the middle of integrating it into the codebase and getting all the features migrated before I was interrupted by work on other more pressing projects.

Ultimately I want to spent some time on it later this year to push it towards release, and I'm sorry it's taken so long since 0.3 to get to a point where I'm happy with the code again.

**Comment by jcoglan** [comment] 2017-03-10 18:39
I'm going to close this issue since the cause of the original issue has been identified, and so isn't something that needs "fixing" per se.

**Closed by jcoglan** 2017-03-10 18:39 UTC
